kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nfs.fullname" . }}-run
subjects:
  - kind: ServiceAccount
    name: {{ template "nfs.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "nfs.fullname" . }}-runner
  apiGroup: rbac.authorization.k8s.io
