kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rancher-nfs
  {{- if .Values.persistence.defaultClass }}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  {{- else }}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
  {{- end }}
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: rancher.io/nfs
